### ISSUE TITLE
Updated Precision Math

### ISSUE THREAD

**Issue by SMSum** [giinuu/precision-alignment#1]
Hello there, I noticed you forked off my repo! This repo is highly outdated from the finalized version. If you want the last version I'd love to get in contact. Thanks!

**Comment by giinuu** [comment]
> Hello there, I noticed you forked off my repo! This repo is highly outdated from the finalized version. If you want the last version I'd love to get in contact. Thanks!

Hi SMSum, thanks for getting in contact - happy to discuss the finalized version you have. unfortunately it seems like github doesn't provide any private method of chatting, my details can be found via the workshop page (should probably add that to the repo!);

https://steamcommunity.com/sharedfiles/filedetails/?id=2931914946

**Comment by giinuu** [comment]
Closed for now, happy to re-open and merge changes if finalized source code is found.
